#############################################################################
# Makefile for building: Calculator
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  ../Calculator/Calculator.pro
# Template: app
# Command: /run/current-system/sw/bin/qmake -o Makefile ../Calculator/Calculator.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../Calculator -I. -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore -I. -I/nix/store/d1q8k4ranmk4rq5mzlrpmji07p4yflb8-libglvnd-1.3.4-dev/include -I. -I/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/linux-g++
QMAKE         = /run/current-system/sw/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /run/current-system/sw/bin/qmake -install qinstall
QINSTALL_PROGRAM = /run/current-system/sw/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Calculator1.0.0
DISTDIR = /home/duck/build-Calculator-Desktop-Debug/.tmp/Calculator1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/nix/store/wl14gkv0hppzws9i8v25xz314n6aqaqn-qtwebkit-5.212.0-alpha4/lib -Wl,-rpath,/nix/store/wl14gkv0hppzws9i8v25xz314n6aqaqn-qtwebkit-5.212.0-alpha4/lib -Wl,-rpath,/nix/store/5786l119qqaa0g6yr4dysr22vd5w9cay-qtbase-5.15.3/lib
LIBS          = $(SUBLIBS) -L/nix/store/1imqkzgy63haif5vrdsg3i8gmqm9f9kk-libGL-1.3.4/lib /nix/store/5786l119qqaa0g6yr4dysr22vd5w9cay-qtbase-5.15.3/lib/libQt5Widgets.so /nix/store/5786l119qqaa0g6yr4dysr22vd5w9cay-qtbase-5.15.3/lib/libQt5Gui.so /nix/store/5786l119qqaa0g6yr4dysr22vd5w9cay-qtbase-5.15.3/lib/libQt5Core.so -L/nix/store/i4rmd8dk8xmpmblkl78pw8iim9byj6yi-libglvnd-1.3.4/lib -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Calculator/main.cpp \
		../Calculator/calculator.cpp moc_calculator.cpp
OBJECTS       = main.o \
		calculator.o \
		moc_calculator.o
DIST          = /nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/spec_pre.prf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/unix.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/linux.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/sanitize.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/gcc-base.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/gcc-base-unix.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/g++-base.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/g++-unix.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/qconfig.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3danimation.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dcore.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dextras.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dinput.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dlogic.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquick.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3drender.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3drender_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bluetooth.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_charts.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_charts_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_concurrent.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_core.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_core_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_dbus.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_dbus_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designer.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designer_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_edid_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_gui.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_gui_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_help.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_help_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_input_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_location.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_location_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimedia.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_network.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_network_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_nfc.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_nfc_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_opengl.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_opengl_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_openglextensions.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdf.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdf_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioning.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioning_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioningquick.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_printsupport.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qml.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qml_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlmodels.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmltest.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quick.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quick_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_script.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_script_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_scripttools.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sensors.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sensors_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_serialport.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_serialport_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_service_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sql.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sql_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_svg.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_svg_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_testlib.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_testlib_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uiplugin.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uitools.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uitools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandclient.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webchannel.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webengine.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webengine_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecore.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkit.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkit_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_websockets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_websockets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webview.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webview_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_widgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_widgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_x11extras.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xml.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xml_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt_functions.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt_config.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/linux-g++/qmake.conf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/spec_post.prf \
		../Calculator/.qmake.stash \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/exclusive_builds.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/toolchain.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/default_pre.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resolve_config.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/default_post.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qml_debug.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/warn_on.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resources_functions.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resources.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/moc.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/unix/opengl.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/uic.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/unix/thread.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qmake_use.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/file_copies.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/testcase_targets.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/exceptions.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/yacc.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/lex.prf \
		../Calculator/Calculator.pro ../Calculator/calculator.h ../Calculator/main.cpp \
		../Calculator/calculator.cpp
QMAKE_TARGET  = Calculator
DESTDIR       = 
TARGET        = Calculator


first: all
####### Build rules

Calculator: ui_calculator.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Calculator/Calculator.pro /nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/linux-g++/qmake.conf /nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/spec_pre.prf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/unix.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/linux.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/sanitize.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/gcc-base.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/gcc-base-unix.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/g++-base.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/g++-unix.conf \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/qconfig.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3danimation.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dcore.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dextras.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dinput.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dlogic.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquick.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3drender.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3drender_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bluetooth.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_charts.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_charts_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_concurrent.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_core.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_core_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_dbus.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_dbus_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designer.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designer_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_edid_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_gui.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_gui_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_help.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_help_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_input_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_location.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_location_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimedia.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_network.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_network_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_nfc.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_nfc_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_opengl.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_opengl_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_openglextensions.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdf.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdf_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioning.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioning_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioningquick.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_printsupport.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qml.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qml_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlmodels.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmltest.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quick.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quick_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_script.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_script_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_scripttools.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sensors.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sensors_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_serialport.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_serialport_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_service_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sql.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sql_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_svg.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_svg_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_testlib.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_testlib_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uiplugin.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uitools.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uitools_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandclient.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webchannel.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webengine.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webengine_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecore.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkit.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkit_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_websockets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_websockets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webview.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webview_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_widgets.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_widgets_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_x11extras.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xml.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xml_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt_functions.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt_config.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/linux-g++/qmake.conf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/exclusive_builds.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/toolchain.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/default_pre.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resolve_config.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/default_post.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qml_debug.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/warn_on.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resources_functions.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resources.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/moc.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/unix/opengl.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/uic.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/unix/thread.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qmake_use.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/file_copies.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/testcase_targets.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/exceptions.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/yacc.prf \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/lex.prf \
		../Calculator/Calculator.pro
	$(QMAKE) -o Makefile ../Calculator/Calculator.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/spec_pre.prf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/unix.conf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/linux.conf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/sanitize.conf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/gcc-base.conf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/gcc-base-unix.conf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/g++-base.conf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/common/g++-unix.conf:
/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/qconfig.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3danimation.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3danimation_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dcore.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dcore_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dextras.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dextras_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dinput.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dinput_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dlogic.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquick.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquick_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickextras.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickinput.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickrender.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3drender.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_3drender_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bluetooth.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_charts.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_charts_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_concurrent.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_concurrent_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_core.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_core_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_dbus.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_dbus_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designer.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designer_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_edid_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_egl_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_fb_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_glx_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_gui.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_gui_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_help.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_help_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_input_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_location.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_location_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimedia.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimedia_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_network.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_network_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_nfc.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_nfc_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_opengl.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_opengl_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_openglextensions.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdf.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdf_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdfwidgets.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioning.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioning_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioningquick.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_positioningquick_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_printsupport.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_printsupport_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qml.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qml_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlmodels.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmltest.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmltest_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quick.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quick_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickshapes_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quicktemplates2.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickwidgets.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_script.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_script_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_scripttools.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_scripttools_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sensors.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sensors_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_serialport.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_serialport_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_service_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sql.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_sql_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_svg.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_svg_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_testlib.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_testlib_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_theme_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uiplugin.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uitools.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_uitools_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandclient.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandclient_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandcompositor.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webchannel.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webchannel_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webengine.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webengine_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecore.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkit.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkit_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkitwidgets.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_websockets.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_websockets_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webview.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_webview_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_widgets.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_widgets_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_x11extras.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_x11extras_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xml.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xml_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt_functions.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt_config.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/linux-g++/qmake.conf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/spec_post.prf:
.qmake.stash:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/exclusive_builds.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/toolchain.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/default_pre.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resolve_config.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/default_post.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qml_debug.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/warn_on.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qt.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resources_functions.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/resources.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/moc.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/unix/opengl.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/uic.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/unix/thread.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/qmake_use.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/file_copies.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/testcase_targets.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/exceptions.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/yacc.prf:
/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/features/lex.prf:
../Calculator/Calculator.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ../Calculator/Calculator.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile Calculator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Calculator/calculator.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Calculator/main.cpp ../Calculator/calculator.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Calculator/calculator.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_calculator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calculator.cpp
moc_calculator.cpp: ../Calculator/calculator.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QMainWindow \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qmainwindow.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtwidgetsglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtguiglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qconfig-bootstrapped.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qconfig.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtcore-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsystemdetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qprocessordetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcompilerdetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtypeinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsysinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlogging.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qflags.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbasicatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_bootstrap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qgenericatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_cxx11.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_msvc.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qglobalstatic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmutex.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qnumeric.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qversiontagging.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtgui-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtwidgets-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qwindowdefs.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobjectdefs.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qnamespace.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobjectdefs_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qwindowdefs_win.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobject.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstring.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qchar.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbytearray.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qrefcount.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qarraydata.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringliteral.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringalgorithms.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringview.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringbuilder.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qalgorithms.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qiterator.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qhashfunctions.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qpair.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvector.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontainertools_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qpoint.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbytearraylist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringlist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qregexp.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringmatcher.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcoreevent.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qscopedpointer.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmetatype.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvarlengtharray.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontainerfwd.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobject_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmargins.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpaintdevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qrect.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsize.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpalette.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qcolor.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qrgb.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qrgba64.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qbrush.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qmatrix.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpolygon.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qregion.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qdatastream.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qiodevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qline.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtransform.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qimage.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpixelformat.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpixmap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsharedpointer.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qshareddata.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qhash.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsharedpointer_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfont.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfontmetrics.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfontinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qsizepolicy.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qcursor.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qkeysequence.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qevent.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvariant.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qdebug.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtextstream.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlocale.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qset.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontiguouscache.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qurl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qurlquery.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qfile.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qfiledevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qvector2d.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtouchdevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtabwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qicon.h \
		moc_predefs.h \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/bin/moc
	/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/bin/moc $(DEFINES) --include /home/duck/build-Calculator-Desktop-Debug/moc_predefs.h -I/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/mkspecs/linux-g++ -I/home/duck/Calculator -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui -I/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore -I. -I/nix/store/6r5h4h7nqx73m87j5b9sjwy2x9kyri0k-gcc-10.3.0/include/c++/10.3.0 -I/nix/store/6r5h4h7nqx73m87j5b9sjwy2x9kyri0k-gcc-10.3.0/include/c++/10.3.0/x86_64-unknown-linux-gnu -I/nix/store/6r5h4h7nqx73m87j5b9sjwy2x9kyri0k-gcc-10.3.0/include/c++/10.3.0/backward -I/nix/store/6r5h4h7nqx73m87j5b9sjwy2x9kyri0k-gcc-10.3.0/lib/gcc/x86_64-unknown-linux-gnu/10.3.0/include -I/nix/store/6r5h4h7nqx73m87j5b9sjwy2x9kyri0k-gcc-10.3.0/include -I/nix/store/6r5h4h7nqx73m87j5b9sjwy2x9kyri0k-gcc-10.3.0/lib/gcc/x86_64-unknown-linux-gnu/10.3.0/include-fixed -I/nix/store/msy4nj4gscw9csc82labx0xvh7vqlfif-glibc-2.33-117-dev/include ../Calculator/calculator.h -o moc_calculator.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_calculator.h
compiler_uic_clean:
	-$(DEL_FILE) ui_calculator.h
ui_calculator.h: ../Calculator/calculator.ui \
		/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/bin/uic
	/nix/store/fhpz3nv1j7l2sa0nc72sy6ww14m6hz54-qt-full-5.15.3/bin/uic ../Calculator/calculator.ui -o ui_calculator.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../Calculator/main.cpp ../Calculator/calculator.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QMainWindow \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qmainwindow.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtwidgetsglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtguiglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qconfig-bootstrapped.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qconfig.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtcore-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsystemdetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qprocessordetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcompilerdetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtypeinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsysinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlogging.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qflags.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbasicatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_bootstrap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qgenericatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_cxx11.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_msvc.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qglobalstatic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmutex.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qnumeric.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qversiontagging.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtgui-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtwidgets-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qwindowdefs.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobjectdefs.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qnamespace.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobjectdefs_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qwindowdefs_win.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobject.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstring.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qchar.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbytearray.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qrefcount.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qarraydata.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringliteral.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringalgorithms.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringview.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringbuilder.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qalgorithms.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qiterator.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qhashfunctions.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qpair.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvector.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontainertools_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qpoint.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbytearraylist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringlist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qregexp.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringmatcher.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcoreevent.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qscopedpointer.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmetatype.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvarlengtharray.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontainerfwd.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobject_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmargins.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpaintdevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qrect.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsize.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpalette.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qcolor.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qrgb.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qrgba64.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qbrush.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qmatrix.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpolygon.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qregion.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qdatastream.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qiodevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qline.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtransform.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qimage.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpixelformat.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpixmap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsharedpointer.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qshareddata.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qhash.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsharedpointer_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfont.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfontmetrics.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfontinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qsizepolicy.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qcursor.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qkeysequence.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qevent.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvariant.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qdebug.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtextstream.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlocale.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qset.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontiguouscache.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qurl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qurlquery.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qfile.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qfiledevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qvector2d.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtouchdevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtabwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qicon.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QApplication \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qapplication.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcoreapplication.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qeventloop.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qdesktopwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qguiapplication.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Calculator/main.cpp

calculator.o: ../Calculator/calculator.cpp ../Calculator/calculator.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QMainWindow \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qmainwindow.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtwidgetsglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtguiglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qglobal.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qconfig-bootstrapped.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qconfig.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtcore-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsystemdetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qprocessordetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcompilerdetection.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtypeinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsysinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlogging.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qflags.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbasicatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_bootstrap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qgenericatomic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_cxx11.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qatomic_msvc.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qglobalstatic.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmutex.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qnumeric.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qversiontagging.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtgui-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtwidgets-config.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qwindowdefs.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobjectdefs.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qnamespace.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobjectdefs_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qwindowdefs_win.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobject.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstring.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qchar.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbytearray.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qrefcount.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qarraydata.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringliteral.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringalgorithms.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringview.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringbuilder.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qalgorithms.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qiterator.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qhashfunctions.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qpair.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvector.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontainertools_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qpoint.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qbytearraylist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringlist.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qregexp.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qstringmatcher.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcoreevent.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qscopedpointer.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmetatype.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvarlengtharray.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontainerfwd.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qobject_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmargins.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpaintdevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qrect.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsize.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpalette.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qcolor.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qrgb.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qrgba64.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qbrush.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qmatrix.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpolygon.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qregion.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qdatastream.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qiodevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qline.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtransform.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qimage.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpixelformat.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpixmap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsharedpointer.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qshareddata.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qhash.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qsharedpointer_impl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfont.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfontmetrics.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qfontinfo.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qsizepolicy.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qcursor.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qkeysequence.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qevent.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qvariant.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qmap.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qdebug.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qtextstream.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qlocale.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qset.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcontiguouscache.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qurl.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qurlquery.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qfile.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qfiledevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qvector2d.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtouchdevice.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qtabwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qicon.h \
		ui_calculator.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/QVariant \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QApplication \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qapplication.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qcoreapplication.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtCore/qeventloop.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qdesktopwidget.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qguiapplication.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qinputmethod.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QLineEdit \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qlineedit.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qframe.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtextcursor.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtextformat.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qpen.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtGui/qtextoption.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QPushButton \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qpushbutton.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/qabstractbutton.h \
		/nix/store/jmf93x3s00c4x7488h5sk6x1br8m01x4-qtbase-5.15.3-dev/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculator.o ../Calculator/calculator.cpp

moc_calculator.o: moc_calculator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calculator.o moc_calculator.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Calculator/bin || mkdir -p $(INSTALL_ROOT)/opt/Calculator/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Calculator/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Calculator/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Calculator/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

